### ISSUE TITLE
Compilation error: grpc: error while marshaling: proto: Marshal called with nil

### ISSUE THREAD

**Issue by KurtE** [arduino/arduino-cli#1812]
### Describe the problem

Sorry there is probably something screwy in this code, that I am hacking up...

I tried to do a verify operation, and the build aborted with an error:

```
grpc: error while marshaling: proto: Marshal called with nil

Compilation error: grpc: error while marshaling: proto: Marshal called with nil
```
That was all of the output, all in orangish color. 

I have no idea what that error is supposed to imply.

### To reproduce

Not sure, but I included the code...  Note: this code is not done yet, nor may never be used, but just an experiment on Teensy 3.2, to see if I can use FTM timer to capture pulse widths and maybe generate specific pulses...

I simply clicked on verify with this sketch, which includes a header file, which is part of the sketch.

[t3x_test_ftm_pin_capture-220717a.zip](https://github.com/arduino/arduino-ide/files/9128089/t3x_test_ftm_pin_capture-220717a.zip)

### Expected behavior

I am guessing probably lots of error messages.

### Arduino IDE version

20220716

### Operating system

Windows

### Operating system version

Windows 10

### Additional context

I am running with yesterdays IDE did not see any updates for today.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
I determined this is a bug in the Arduino CLI codebase, so I have moved the issue to the appropriate repository.

I bisected the issue to a5466d017f7767226b090ed9d3e0b8a74617e0da

In case it will be useful, I will provide instructions for reproducing the issue using the Arduino CLI gRPC interface directly (the issue does not occur when using the Arduino CLI command line interface).
#### Set up

```text
$ arduino-cli version
arduino-cli.exe  Version: 0.25.1-rc1 Commit: 436f0bb9 Date: 2022-07-22T15:47:42Z

$ arduino-cli sketch new /tmp/FooSketch

$ arduino-cli daemon
```

#### Demo

Use [grpcurl](https://github.com/fullstorydev/grpcurl) to run the following commands in another terminal:

```text
$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.Create

{
  "instance": {
    "id": 1
  }
}

$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  -d '{"instance": {"id": 1}}' \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.Init

$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  -d '{"instance": {"id": 1}, "name": "SD", "version": "1.2.4"}' \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.LibraryInstall

ERROR:
  Code: Unknown
  Message: destination dir C:\Users\per\AppData\Local\Temp\arduino-cli-directories-user\libraries\SD already exists, cannot install

$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  -d '{"instance": {"id": 1}}' \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.Init

$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  -d '{"instance": {"id": 1}, "sketch_path": "/tmp/FooSketch"}' \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.Compile

ERROR:
  Code: Internal
  Message: grpc: error while marshaling: proto: Marshal called with nil
```
